language: c
sudo: required
script: curl -L https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh | sh
os:
- linux
- osx
env:
  global:
  - OCAML_VERSION=4.07
matrix:
  fast_finish: true
  allow_failures:
  - os: osx
before_cache: if [ $TRAVIS_OS_NAME = osx ]; then brew cleanup; fi
cache:
  apt: true
  directories:
  - $HOME/.opam
  - $HOME/Library/Caches/Homebrew
