version: 2.1

defaults: &defaults
  docker:
  - image: coqorg/coq:8.10
  environment:
    OPAMVERBOSE: 1
    OPAMWITHTEST: true
    OPAMYES: true
    TERM: xterm

commands:
  startup:
    steps:
    - checkout
    - run:
        name: Configure environment
        command: echo . ~/.profile >> $BASH_ENV
  build:
    steps:
    - checkout
    - run:
        name: Configure environment
        command: echo . ~/.profile >> $BASH_ENV
    - run:
        name: Install dependencies
        command: |
          opam update
          opam install --deps-only ./
    - run:
        name: List installed packages
        command: opam list
    - run:
        name: Build and test
        command: opam install .
    - run:
        name: Uninstall
        command: opam remove .

jobs:
  ocaml 4_05:
    <<: *defaults
    steps:
    - startup
    - build
  ocaml 4_07:
    <<: *defaults
    steps:
    - startup
    - run: opam switch 4.07.1+flambda
    - build

workflows:
  version: 2
  build:
    jobs:
    - ocaml 4_05
    - ocaml 4_07
